# -*- coding: utf-8 -*-
"""Exercício 1 - Calculadora simples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3N82hpoN7qm5BAmHg1vMxmBeqdTUwCU
"""

# Calculadora simples
# Exibe apenas 2 números decimais

# Inicia com 2 valores:
validador = 1
while validador == 1:
  num1 = input("Digite um número: ")
  operador = input("Escolha um operador: '+', '-', '*' ou '/' ")
  num2 = input("Digite outro número para realizar a operação: ")
  validador = 0

# Verifica se a operação é válida:
  try:
      num1, num2 = float(num1), float(num2)
  except:
      print("Operação inválida")
      validador = 1

# Verifica os operadores:
if operador == '+':
    resultado = num1 + num2
elif operador == '-':
    resultado = num1 - num2
elif operador == '*':
    resultado = num1 * num2
elif operador == '/' and num2 != 0:
    resultado = num1 / num2
elif operador == '/' and num2 == 0:
    print("Não é possível dividir por 0")
    resultado = 0
else:
    print("Operação inválida")

# Resultado 1:
print("Resultado: ", round(resultado, 2))

# Continua a operação:
while validador == 0:
  operador = input("Digite 'exit' para sair ou digite mais um operador para continuar: '+', '-', '*' ou '/' :")

  # Verifica se o usuário quer sair da aplicação ou não
  if operador == 'exit':
      validador = 1
  else:
    num3 = input("Digite outro número para realizar a operação: ")

    try:
      num3 = float(num3)

      if operador == '+':
        resultado = resultado + num3
      elif operador == '-':
          resultado = resultado - num3
      elif operador == '*':
          resultado = resultado * num3
      elif operador == '/' and num3 != 0:
          resultado = resultado / num3
      elif operador == '/' and num365 == 0:
          print("Não é possível dividir por 0")
          resultado = 0
      else:
        print("Operação inválida")

    except:
      print("Operação inválida")

    # Resultados posteriores:
    print("Resultado: ", round(resultado, 2))

# Encerra o programa com o fim do loop